# Generated by Django 6.0.3 on 2026-03-27 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número de pedido')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('country', models.CharField(default='Colombia', max_length=100, verbose_name='País')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('address', models.TextField(verbose_name='Dirección completa')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Código postal')),
                ('notes', models.TextField(blank=True, verbose_name='Notas del pedido')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de envío')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('processing', 'En preparación'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Estado')),
                ('payment_method', models.CharField(choices=[('wompi', 'Wompi'), ('transfer', 'Transferencia'), ('cash', 'Efectivo'), ('other', 'Otro')], default='wompi', max_length=20, verbose_name='Método de pago')),
                ('payment_status', models.CharField(blank=True, max_length=50, verbose_name='Estado del pago')),
                ('wompi_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID transacción Wompi')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Número de guía')),
                ('carrier', models.CharField(blank=True, max_length=100, verbose_name='Transportadora')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pagado en')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado en')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('product_slug', models.CharField(blank=True, max_length=250, verbose_name='Slug del producto')),
                ('variant_info', models.CharField(blank=True, max_length=100, verbose_name='Variante (talla / color)')),
                ('sku', models.CharField(blank=True, max_length=80, verbose_name='SKU')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio unitario')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total línea')),
                ('image_url', models.URLField(blank=True, verbose_name='URL imagen')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Línea de pedido',
                'verbose_name_plural': 'Líneas de pedido',
            },
        ),
    ]
