# Generated by Django 6.0.3 on 2026-03-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Palma Cayena', max_length=100, verbose_name='Nombre del sitio')),
                ('site_tagline', models.CharField(blank=True, default='Born from the sea.', max_length=200, verbose_name='Tagline')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/', verbose_name='Logo')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='brand/', verbose_name='Logo oscuro')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='brand/', verbose_name='Favicon')),
                ('email', models.EmailField(blank=True, default='hola@palmacayena.com', max_length=254, verbose_name='Email de contacto')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, default='Cartagena, Colombia', max_length=100, verbose_name='Ciudad')),
                ('default_meta_title', models.CharField(blank=True, max_length=160, verbose_name='Meta title por defecto')),
                ('default_meta_description', models.TextField(blank=True, verbose_name='Meta description por defecto')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='Google Analytics ID')),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=50, verbose_name='Facebook Pixel ID')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Modo mantenimiento')),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=250000, max_digits=12, verbose_name='Envío gratis desde (COP)')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=15000, max_digits=10, verbose_name='Costo de envío estándar (COP)')),
                ('currency', models.CharField(default='COP', max_length=10, verbose_name='Moneda')),
                ('currency_symbol', models.CharField(default='$', max_length=5, verbose_name='Símbolo de moneda')),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('pinterest', 'Pinterest'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp')], max_length=20, verbose_name='Plataforma')),
                ('url', models.URLField(max_length=300, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Red social',
                'verbose_name_plural': 'Redes sociales',
                'ordering': ['order'],
            },
        ),
    ]
