# Generated by Django 6.0.3 on 2026-03-27 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(default='wompi', max_length=30, verbose_name='Pasarela')),
                ('transaction_id', models.CharField(blank=True, max_length=150, verbose_name='ID transacción')),
                ('reference', models.CharField(blank=True, max_length=150, unique=True, verbose_name='Referencia')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('currency', models.CharField(default='COP', max_length=10, verbose_name='Moneda')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('declined', 'Rechazado'), ('voided', 'Anulado'), ('error', 'Error')], default='pending', max_length=20, verbose_name='Estado')),
                ('gateway_response', models.JSONField(blank=True, null=True, verbose_name='Respuesta de pasarela')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
    ]
