# Generated by Django 6.0.3 on 2026-03-27 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Imagen')),
                ('image_alt', models.CharField(blank=True, max_length=200, verbose_name='Alt imagen')),
                ('meta_title', models.CharField(blank=True, max_length=160, verbose_name='Meta title')),
                ('meta_description', models.TextField(blank=True, max_length=320, verbose_name='Meta description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('story', models.TextField(blank=True, verbose_name='Historia de la colección')),
                ('image', models.ImageField(blank=True, null=True, upload_to='collections/', verbose_name='Imagen principal')),
                ('image_alt', models.CharField(blank=True, max_length=200, verbose_name='Alt imagen')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='collections/banners/', verbose_name='Banner')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacada')),
                ('launch_date', models.DateField(blank=True, null=True, verbose_name='Fecha de lanzamiento')),
                ('meta_title', models.CharField(blank=True, max_length=160, verbose_name='Meta title')),
                ('meta_description', models.TextField(blank=True, max_length=320, verbose_name='Meta description')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Colección',
                'verbose_name_plural': 'Colecciones',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('hex_code', models.CharField(blank=True, help_text='Ej: #FF5733', max_length=7, verbose_name='Código HEX')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Talla')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Descripción')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Talla',
                'verbose_name_plural': 'Tallas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Etiqueta')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug')),
                ('sku', models.CharField(blank=True, max_length=50, unique=True, verbose_name='SKU base')),
                ('short_description', models.TextField(blank=True, help_text='Aparece en el listado y encabezado del producto', verbose_name='Descripción corta')),
                ('description', models.TextField(blank=True, verbose_name='Descripción completa')),
                ('care_instructions', models.TextField(blank=True, verbose_name='Instrucciones de cuidado')),
                ('composition', models.CharField(blank=True, max_length=300, verbose_name='Composición / Materiales')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio (COP)')),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio antes del descuento', max_digits=12, null=True, verbose_name='Precio comparado (COP)')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('draft', 'Borrador'), ('archived', 'Archivado')], default='active', max_length=20, verbose_name='Estado')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('is_new', models.BooleanField(default=True, verbose_name='Nuevo')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Más vendido')),
                ('meta_title', models.CharField(blank=True, max_length=160, verbose_name='Meta title')),
                ('meta_description', models.TextField(blank=True, max_length=320, verbose_name='Meta description')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='products/og/', verbose_name='OG Image (redes sociales)')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Peso (kg)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden manual')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category', verbose_name='Categoría')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.collection', verbose_name='Colección')),
                ('colors', models.ManyToManyField(blank=True, to='shop.color', verbose_name='Colores disponibles')),
                ('sizes', models.ManyToManyField(blank=True, to='shop.size', verbose_name='Tallas disponibles')),
                ('tags', models.ManyToManyField(blank=True, to='shop.tag', verbose_name='Etiquetas')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Imagen')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo')),
                ('is_main', models.BooleanField(default=False, verbose_name='Imagen principal')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de producto',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=80, unique=True, verbose_name='SKU variante')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Si se completa, reemplaza el precio del producto', max_digits=12, null=True, verbose_name='Precio especial')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.color', verbose_name='Color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product', verbose_name='Producto')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.size', verbose_name='Talla')),
            ],
            options={
                'verbose_name': 'Variante',
                'verbose_name_plural': 'Variantes',
                'unique_together': {('product', 'size', 'color')},
            },
        ),
    ]
