# Generated by Django 6.0.3 on 2026-03-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('truck', 'Envío'), ('shield', 'Pago seguro'), ('refresh', 'Devoluciones'), ('heart', 'Calidad'), ('star', 'Exclusividad'), ('leaf', 'Sostenibilidad')], default='star', max_length=20, verbose_name='Ícono')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Beneficio',
                'verbose_name_plural': 'Beneficios',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('is_read', models.BooleanField(default=False, verbose_name='Leído')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Respondido en')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensaje de contacto',
                'verbose_name_plural': 'Mensajes de contacto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('shipping', 'Envíos'), ('returns', 'Cambios y devoluciones'), ('sizing', 'Tallas'), ('payments', 'Pagos'), ('products', 'Productos'), ('general', 'General')], default='general', max_length=20, verbose_name='Categoría')),
                ('question', models.CharField(max_length=300, verbose_name='Pregunta')),
                ('answer', models.TextField(verbose_name='Respuesta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Pregunta frecuente',
                'verbose_name_plural': 'Preguntas frecuentes',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo')),
                ('cta_text', models.CharField(default='Explorar colección', max_length=80, verbose_name='Texto del botón')),
                ('cta_url', models.CharField(default='/tienda/', max_length=200, verbose_name='URL del botón')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='Imagen de fondo')),
                ('image_alt', models.CharField(blank=True, max_length=200, verbose_name='Alt imagen')),
                ('video_url', models.URLField(blank=True, verbose_name='URL de video (mp4)')),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Color del texto')),
                ('overlay_opacity', models.DecimalField(decimal_places=2, default=0.3, max_digits=3, verbose_name='Opacidad del overlay')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Hero section',
                'verbose_name_plural': 'Hero sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomepageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('storytelling', 'Storytelling de marca'), ('benefits', 'Bloque de beneficios'), ('editorial', 'Editorial / Lookbook'), ('instagram', 'Bloque Instagram'), ('quote', 'Cita / Frase'), ('banner', 'Banner promocional'), ('custom', 'Bloque personalizado')], max_length=30, verbose_name='Tipo')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=400, verbose_name='Subtítulo')),
                ('body_text', models.TextField(blank=True, verbose_name='Texto principal')),
                ('cta_text', models.CharField(blank=True, max_length=80, verbose_name='Texto CTA')),
                ('cta_url', models.CharField(blank=True, max_length=200, verbose_name='URL CTA')),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/', verbose_name='Imagen')),
                ('image_secondary', models.ImageField(blank=True, null=True, upload_to='homepage/', verbose_name='Imagen secundaria')),
                ('image_alt', models.CharField(blank=True, max_length=200, verbose_name='Alt imagen')),
                ('bg_color', models.CharField(blank=True, default='', max_length=7, verbose_name='Color de fondo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Bloque homepage',
                'verbose_name_plural': 'Bloques homepage',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='JournalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('excerpt', models.TextField(blank=True, verbose_name='Extracto')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='journal/', verbose_name='Imagen portada')),
                ('cover_image_alt', models.CharField(blank=True, max_length=200, verbose_name='Alt imagen')),
                ('author', models.CharField(default='Palma Cayena', max_length=100, verbose_name='Autora')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('meta_title', models.CharField(blank=True, max_length=160, verbose_name='Meta title')),
                ('meta_description', models.TextField(blank=True, max_length=320, verbose_name='Meta description')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Post del journal',
                'verbose_name_plural': 'Journal',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('source', models.CharField(blank=True, default='homepage', max_length=50, verbose_name='Fuente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Suscriptor newsletter',
                'verbose_name_plural': 'Suscriptores newsletter',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('about', 'Nosotras'), ('shipping', 'Envíos'), ('returns', 'Cambios y devoluciones'), ('terms', 'Términos y condiciones'), ('privacy', 'Política de privacidad'), ('contact', 'Contacto'), ('custom', 'Personalizada')], default='custom', max_length=20, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Contenido HTML')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Imagen hero')),
                ('hero_image_alt', models.CharField(blank=True, max_length=200, verbose_name='Alt imagen hero')),
                ('meta_title', models.CharField(blank=True, max_length=160, verbose_name='Meta title')),
                ('meta_description', models.TextField(blank=True, max_length=320, verbose_name='Meta description')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicada')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('text', models.TextField(verbose_name='Testimonio')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Rating')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Foto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
